steps:
  # Step to set up Go
  - name: 'golang:1.20'
    id: 'setup-go'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        go version

  # Step to install GoReleaser
  - name: 'alpine:latest'
    id: 'install-goreleaser'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache curl
        curl -sL https://git.io/goreleaser | sh

  # Step to run GoReleaser
  - name: 'alpine:latest'
    id: 'run-goreleaser'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        goreleaser --config .goreleaser.yaml
