steps:
  # Step to set up Go environment
  - name: 'golang:1.20'
    id: 'setup-go'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        go version

  # Step to install GoReleaser
  - name: 'alpine:latest'
    id: 'install-goreleaser'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache curl git
        curl -sL https://git.io/goreleaser | sh

  # Step to fetch Git tags (if needed)
  - name: 'alpine:latest'
    id: 'fetch-git-tags'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apk add --no-cache git
        git fetch --tags

  # Step to run GoReleaser
  - name: 'alpine:latest'
    id: 'run-goreleaser'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        goreleaser --config .goreleaser.yaml
