steps:
  - name: 'goreleaser/goreleaser:latest'
    id: 'run-goreleaser'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        goreleaser --config .goreleaser.yaml

timeout: 1200s  # Optional: Increase timeout if necessary
options:
  logging: CLOUD_LOGGING_ONLY