steps:
  # Install Go (if needed)
  - name: 'golang:1.20'
    entrypoint: 'go'
    args: ['version']

  # Install GoReleaser
  - name: 'golang:1.20'
    entrypoint: 'go'
    args: ['install', 'github.com/goreleaser/goreleaser@latest']
    env:
      - 'GO111MODULE=on'










# Set the timeout for the build (optional)
timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY

  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/dev-docs-pool'