steps:
  # Step 1: Set up Go environment with Go 1.23.0
  - name: 'golang:1.23.0'
    id: 'setup-go'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        go version
        go mod download  # Download Go module dependencies

  # Step 2: Run GoReleaser using its Docker image
  - name: 'goreleaser/goreleaser:latest'
    id: 'run-goreleaser'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        goreleaser --config .goreleaser.yaml --snapshot

  # Step 3: Get the tag name from the git push command
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-tag-name'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG_NAME=$(git describe --tags --abbrev=0)
        echo "TAG_NAME=${TAG_NAME}" >> $BASH_ENV

artifacts:
  objects:
    location: 'gs://bucket_name/main/${TAG_NAME}/'
    paths: ['dist/**']
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/dev-docs-pool'