steps:
  - name: 'goreleaser/goreleaser'  # GoReleaser Docker image
    id: 'release'
    entrypoint: 'bash'
    args:
    - goreleaser release --config .goreleaser.yaml

timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY