steps:
  # Step 1: Set up Go environment with Go 1.23.0
  - name: 'golang:1.23.0'
    id: 'setup-go'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        go version
        go mod download

  # Step 2: Run GoReleaser using its Docker image
  - name: 'goreleaser/goreleaser:latest'
    id: 'run-goreleaser'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        goreleaser release --clean

  # Step 3: Upload dist to storage
  - id: "Upload dist to storage"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    automapSubstitutions: true
    script: |
      #!/usr/bin/env bash
      if [ ! -z "$TAG_NAME" ]; then
        gcloud storage cp ./dist/* gs://dev-docs-releases/main/"$TAG_NAME"
      elif
        gcloud storage cp ./dist/* gs://dev-docs-releases/dist

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/dev-docs-pool'