  - name: 'golang:1.20'
    id: 'setup-go'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y golang-go
        go mod edit -go 1.20
        go version
        go mod download









# Set the timeout for the build (optional)
timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY

  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/dev-docs-pool'