steps:
  # Install Go (if needed)
  - - name: 'golang:1.23.0'
    id: 'setup-go'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        go version
        go mod download

  # Install GoReleaser
  - name: 'golang:1.23.0'
    entrypoint: 'go'
    args: ['install', 'github.com/goreleaser/goreleaser@latest']
    env:
      - 'GO111MODULE=on'

  # Run GoReleaser
  - name: 'golang:1.23.0'
    entrypoint: 'goreleaser'
    args: ['release', '--rm-dist']
    env:
      - 'GOPATH=/workspace/go'
      - 'GOBIN=/workspace/go/bin'
      - 'GITHUB_REF=refs/tags/${_TAG_NAME}'

  # Upload artifacts to Google Cloud Storage
  - id: "Upload dist to storage"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    automapSubstitutions: true
    script: |
      #!/usr/bin/env bash
      if [ ! -z "$TAG_NAME" ]; then
        gcloud storage cp ./dist/* gs://dev-docs-releases/main/{{$TAG_NAME}}/

# Set the timeout for the build (optional)
timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY

  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/dev-docs-pool'
  env:
    - 'PATH=/workspace/go/bin:$$PATH'

  env:
    - 'PATH=/workspace/go/bin:$$PATH'