steps:
  # Step to set up Go environment
  - name: 'golang:1.23.0'
    id: 'setup-go'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Setting up Go environment..."
        go version

  # Step to install GoReleaser
  - name: 'alpine:latest'
    id: 'install-goreleaser'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Installing GoReleaser..."
        apk add --no-cache curl git
        curl -sL https://git.io/goreleaser | sh

  # Step to fetch Git tags (if needed)
  - name: 'alpine:latest'
    id: 'fetch-git-tags'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Fetching Git tags..."
        apk add --no-cache git
        git fetch --tags

  # Step to run GoReleaser using the script file
  - name: 'alpine:latest'
    id: 'run-goreleaser'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Running GoReleaser script..."
        sh run-goreleaser.sh

options:
  logging: 'CLOUD_LOGGING_ONLY'
