steps:
  # Install Go
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', '.']
    env: ['GO111MODULE=on']

  # Install GoReleaser
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', 'github.com/goreleaser/goreleaser@latest']
    env: ['GO111MODULE=on']

  # Run GoReleaser
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'goreleaser'
    args: ['release', '--rm-dist']
    env:
      - 'GOPATH=/workspace/go'
      - 'GOBIN=/workspace/go/bin'
      - 'PATH=/workspace/go/bin:$PATH'

  # Upload artifacts to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'dist/*', 'gs://your-bucket-name/']

# Set the timeout for the build (optional)
timeout: '1800s'